[tool.poetry]
name = "cappuccino-discord"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = "^1.3.0"
sqlalchemy = { version = "^1.3.0", extras=["postgresql"] }
alembic = "^1.4.0"
pyyaml = "^5.3"
sentry-sdk = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
