bot:
  command_prefix: '.'

discord:
  token: ''

database:
  # https://docs.sqlalchemy.org/en/13/core/engines.html#postgresql
  uri: ''

# Plugins listed here will be loaded in order of appearance, child nodes are used as that plugin's configuration.
extensions:
  botui:
  profiles:
  catfacts:
    limit: 1000
    max_length: 200
