bot:
  token: ''
  command_prefix: '.'
  ## If true, other bots will be able to trigger commands.
  # ignore_bots: false

database:
  ## SQLAlchemy connection URL. Only PostgreSQL is *officially* supported.
  ## https://docs.sqlalchemy.org/en/13/core/engines.html#postgresql
  uri: ''

redis:
  ## https://redis-py.readthedocs.io/en/stable/#redis.ConnectionPool.from_url
  uri: ''

## Leave blank if you don't want to use sentry.
sentry:
  dsn: ''

## Plugins listed here will be loaded in order of appearance.
extensions:
  - fun
  - catfacts
