version: 1
root:
  level: INFO
  handlers: [console]
loggers:
  alembic:
    level: INFO
    handlers: [console]
    propagate: false
formatters:
  console:
    format: '%(asctime)s - [%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
